Class {
	#name : 'CBDummyShiftClassBuilder',
	#superclass : 'ShiftClassBuilder',
	#category : 'ChangesBuilder-Tests',
	#package : 'ChangesBuilder',
	#tag : 'Tests'
}

{ #category : 'building' }
CBDummyShiftClassBuilder >> build [

	self error: 'Should not have been built yet'
]

{ #category : 'installing' }
CBDummyShiftClassBuilder >> createClass [

	self error: 'Should not have been built yet'
]

{ #category : 'building' }
CBDummyShiftClassBuilder >> createMetaclass [

	self error: 'Should not have been built yet'
]

{ #category : 'building' }
CBDummyShiftClassBuilder >> createSharedVariables [

	self error: 'Should not have been built yet'
]

{ #category : 'building' }
CBDummyShiftClassBuilder >> installSlotsAndVariables [

	self error: 'Should not have been built yet'
]

{ #category : 'building' }
CBDummyShiftClassBuilder >> tryToFillOldClass [

	self error: 'Should not have been built yet'
]
